"""Add monster_default_health to monster

Revision ID: f05772e5999c
Revises: 6594c1898452
Create Date: 2023-08-10 20:29:20.756749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05772e5999c'
down_revision: Union[str, None] = '6594c1898452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('monster_default_health', sa.Integer(), nullable=True))
    op.drop_column('monsters', 'default_health')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('default_health', sa.INTEGER(), nullable=True))
    op.drop_column('monsters', 'monster_default_health')
    # ### end Alembic commands ###
